columns:
  - id
  - host_id
  - gpu_name
  - gpu_ram
  - num_gpus
#  - cpu_name
#  - cpu_cores_effective
#  - cpu_ram
  - disk_space
  - inet_up
  - inet_down
  - dph_total
  - score
  - reliability
  - geolocation

column_headers:
  id: ID
  host_id: Host
  gpu_name: GPU
  gpu_ram: GPU RAM (GB)
  num_gpus: "# GPUs"
  cpu_name: CPU
  cpu_cores_effective: Cores
  cpu_ram: RAM (GB)
  disk_space: Disk (GB)
  inet_up: Up (Mbps)
  inet_down: Down (Mbps)
  dph_total: $/hr
  score: Score
  reliability: Reliability
  geolocation: Country

column_filters:
#  geolocation: "*, CA"
  gpu_ram: ">= 24576"  # 24 GB in MB
#  gpu_name: "RTX_PRO_6000_WS"

max_rows: 10

disk_size_gb: 100  # Disk space in GB

# Template hashes for various configurations. Select only one at a time.

# ComfyUI (https://cloud.vast.ai/?ref_id=62897&creator_id=62897&name=ComfyUI)
template_hash_id: b3a852d995cac99809607b2f52a2fe36
ui_home_env: /workspace/ComfyUI
# ComfyUI + LTX Video (https://cloud.vast.ai/?ref_id=62897&creator_id=62897&name=ComfyUI%20%2B%20LTX%20Video)
#template_hash_id: 8fdccb872f861b97afce6b0d6ea0e28c
# ComfyUI + Flux.1 (https://cloud.vast.ai/?ref_id=62897&creator_id=62897&name=ComfyUI%20%2B%20FLUX.1)
#template_hash_id: 30fdbc3cad7c0e2737ac9b5c5ef5fbea
# SD WebUI Forge (https://cloud.vast.ai/?ref_id=62897&creator_id=62897&name=SD%20WebUI%20Forge)
#template_hash_id: 4b689515cb5ce3dac12bfdcbe7d7f08f
# SwarmUI (https://cloud.vast.ai/?ref_id=62897&creator_id=62897&name=SwarmUI)
#template_hash_id: 746bfcec4ec615885d5fd02ea717de0a